apiVersion: v1
kind: Deployment
metadata:
  name: myapp-deployment # name of the object we're creating
  labels:
    app: myapp
spec:
  template:   # pod template
    matadta:
      name: nginx-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2 
  selector:
    mathLabels:
      app: myapp
