apiVersion: v1
kind: Service
metadata:
  name: mysql-h
  labels:
    app: mysecure
spec:
  ports:
    - port: 3306
  selector:
    app: mysecure
  clusterIp: None # with this option service not having ip and it's creates a headless svc
