apiVersion: v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysecure
spec:
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysecure
    spec:
      containers:
        - name: mysql-container
          image: mysql # specific full path of image
  replicas: 2
  selector:
    mathLabels:
      app: mysecure
  serviceName: mysql-h # statefulset must required headless service
# podManagementPolicy: Parallel # to overwrite default behaviour of statefulset
